---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: timber-agent
rules:
- apiGroups: ["*"]
  resources:
    - cronjobs
    - daemonsets
    - deployments
    - jobs
    - namespaces
    - pods
    - replicasets
    - statefulsets
  verbs: ["get"]
